### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by Sino0904** [Yushi-Hu/PromptCap#1]
Will the code for training the model be provided? thanks!

**Comment by Yushi-Hu** [comment]
Sure, we will release the training data soon! The training pipeline is in OFA, based on Fairseq

**Comment by Yushi-Hu** [comment]
The training codes are in this repo: https://github.com/OFA-Sys/OFASys. Please follow their fine-tuning instructions. We find eventually it is really hard to incorporate this whole repo into ours so we give up on that plan.
