### ISSUE TITLE
Fine-Tuning?

### ISSUE THREAD

**Issue by ahmadmustafaanis** [Yushi-Hu/PromptCap#7]
How can we fine-tune this model? Is there any script available?

**Comment by Yushi-Hu** [comment]
Hi! The training codes are in this repo: [https://github.com/OFA-Sys/OFASys](https://github.com/OFA-Sys/OFASys). Please follow their fine-tuning instructions. We find eventually it is really hard to incorporate this whole repo into ours so we give up on that plan.
