### ISSUE TITLE
caption_generate_gpt3

### ISSUE THREAD

**Issue by liumc14** [Yushi-Hu/PromptCap#9]
Are you using GPT3 here to generate issue-aware image captions? If so? Do you want to know that each image in the dataset has 5 human-annotated subtitles? Like you mentioned in the paper; or are only the 20 examples here in-context with 5 human-annotated subtitles, and the rest of the images in the dataset still only have one subtitle? If you have time, please give some suggestions
https://github.com/Yushi-Hu/PromptCap/blob/86dd6aaa3fb8961ec256fe9359a3533baa5ceea7/promptcap-gen/caption_gen_greedy.py#L225

**Comment by Yushi-Hu** [comment]
Sorry for the late reply!  Sorry that we still haven't written the docs for writing these captions. 

For here, all coco images come with 5 captions. We concat them as you have seen here for both the 20 in-context examples here and for other images. I believe the examples and test examples should be really similar to make ICL work well
